classes = {
{name = "aabb",type = ".lua"},
{name = "biome_gens",type = ".lua"},
{name = "biome_info",type = ".lua"},
{name = "block_tiles",type = ".png"},
{name = "block",type = ".lua"},
{name = "blocks_info",type = ".lua"},
{name = "camera",type = ".lua"},
{name = "chunk",type = ".lua"},
{name = "controller_action",type = ".lua"},
{name = "controller_movement",type = ".lua"},
{name = "damage_block",type = ".lua"},
{name = "download",type = ".lua"},
{name = "flat_ui",type = ".lua"},
{name = "game",type = ".lua"},
{name = "input_image",type = ".lua"},
{name = "Main",type = ".lua"},
{name = "noise_map",type = ".lua"},
{name = "player",type = ".lua"},
{name = "terrain",type = ".lua"},
{name = "tree",type = ".lua"},
{name = "visibility",type = ".lua"},
{name = "world",type = ".lua"}
{name = "ui",type = ".png"}
}